### ISSUE TITLE
Rear Bearing Hubs

### ISSUE THREAD

**Issue by bryanmonahan** [alexyu132/zcar#1]
hey Alex,  this is an amazing design.  My friend and I have printed a few and are messing around with them

1. found that the rear bearing holders do not maintain hold on the bearings when heated.   am looking at possibly adding a lip around them to maintain control of the bearing, but then must add a washer on the inside to space out the gear from hitting it.

unknown yet.

**Comment by alexyu132** [comment]
What's causing the rear bearings to heat up?

If you switch to the 1.1 branch, I've redesigned the rear bearings to be press fit, which should be less flimsy than the previous design (no lip, but I can add one if there are still loosening issues). You could try switching to that, or look into using a higher temp material like PETG or ABS.

**Comment by bryanmonahan** [comment]
I am using a complete petg build at the moment...

I have no idea whats happening, but myself and another beta tester are having the same issues on two different builds.

1.1 branch...?  sorry, github is new language for me.  ill go dig around.

**Comment by alexyu132** [comment]
If you go to the main page there should be a small dropdown menu on the left that says 'master'. Click that and you can switch to the 1.1 branch.

**Comment by bryanmonahan** [comment]
OK, found.

unknown if this will help.

What is happening, during racing when cornering, the bearings are slipping out under full speed.  the car then exits the turn and alignment is off.   Ive taken to epoxy to keep them in place.   

Ive slammed a small ridge on the inside to help keep the bearing from shifting, and was about to print it till you told me about v1.1  

I think your new design may eliminate it, but unknown what exactly is causing the issue.   Ill print the new version and the rear assembly block it appears to connect to instead of the old method and give that a try.

Thanks for your work with this.

We have also modified the wheels to a simpler design (no spokes) and extended the rear to 11mm.

Looking at modifying the battery cover to create a lower mounting point for the receiver and ESC to lower center of gravity.

This is by far, the simplest and most effective 3d print 1/28th scale car ive found and printed in about 2 years of doing so.   great work.

**Comment by alexyu132** [comment]
Thanks!

Which battery are you using? The one I have pretty much fills the entire battery area so lowering the CG would be difficult without dropping the overall ride height.

**Comment by bryanmonahan** [comment]
a 3.7... but my theory is if i flip it on its side, i can cram the battery esc and rx into the same space,   but thats later.

I am reprinting parts in taulman tech-g now, i like the new rear end idea from 1.1, i think the that connecting the rear hubs to two different axis will result in a lot more stability.

if you would like to talk, im on discord - scapegoatRB#8166, my friend and I would be happy to help you at least destroy parts to see if they work.

**Comment by alexyu132** [comment]
I'd prefer communicating via GitHub issues since it'll make it easier to track problems and suggested improvements. If the new press-fit design fixes the problem, we can close out this issue, but otherwise I can look into adding a lip to the bearing block.
