### ISSUE TITLE
CAD file and assembly instructions

### ISSUE THREAD

**Issue by unauwen** [alexyu132/zcar#2]
Hey, I really like this project and already started printing the components. But I dont know exactly how to assemble the car. Could you add a few pictures of every side? I would like to cusomize it, would it be possible to get the CAD files?
With kind regards
Unauwen

**Comment by alexyu132** [comment]
There are some pictures on the Thingiverse page, as well as an STL of the complete assembly. I designed this in SketchUp, so the CAD file is the SKP file in this repo.

**Comment by unauwen** [comment]
Thanks for your reply, maybe some photos of the back Suspension and/or the front steering would be helpfull for other makers, but I figured it out with trial and error. Thanks for the design
